### ISSUE TITLE
Write up documentation for training/usage

### ISSUE THREAD

**Issue by newsch** [newsch/hairy_plotter#26]
Using the GitHub wiki, write up:
- [ ] CNC.js and how to connect from a laptop, the RPi, etc.
- [ ] using the gcode patcher
- [ ] using the gcode optimizer
- [ ] calibrating pen height, feeds
- [ ] grbl EEPROM settings
- [ ] common problems/troubleshooting
- [ ] illustrator and inkscape gcode plugins
- [ ] illustrator stippling software usage

This should be done by 5/24 in order to allow printing for EXPO, etc.

**Comment by newsch** [comment]
Related to #18
